### ISSUE TITLE
Regular Expressions for Capturing Fuller Fragments

### ISSUE THREAD

**Issue by everitt-andrew** [GatorEducator/gatorgrader#102]
@gkapfham brought up the idea of creating code with more in-depth fragment capture (for expressions). Specifically, he mentioned that a single fragment may not be able to analyze the entirety of certain LaTeX elements such as an enumerated list. Finally, adding this check and those that are similar would allow the system to be useful in additional situations.

**Comment by gkapfham** [comment]
Hello @everitt-andrew, I have transferred this issue to this repository because we would need to add this feature to GatorGrader itself. After talking with @Michionlion we agree that it was best to focus on the issue here.

**Comment by gkapfham** [comment]
Quick notes about this feature: the idea is that a person using GatorGrader should be able to specify a regular expression and then the tool would check to see if the command or file contains contents that match that regular expression. This would help to specify checks like: "contains <div>, any valid HTML, and </div>". This could also be useful for checking for the existence of certain LaTeX environment like enumerations. @miller365 suggested that this should be a separate command-line argument, like `--regexp`, which I think is a really good idea!

**Comment by gkapfham** [comment]
It is important to note that parsing HTML with regular expressions is difficult. As such, if we want to really support this type of check with GatorGrader, then it would make more sense to add a new parameter for HTML fragment checking, say `--html` and then the specific tag or fragment to check.

References:

https://stackoverflow.com/questions/3524364/regular-expression-to-match-closing-html-tags
https://stackoverflow.com/questions/41720896/beautifulsoup-parsing-html-get-part-of-href

With that said, I think that it might be a good idea to support simple regular expressions because of the fact that they would still add a lot of flexibility to GatorGrader's checking. It would place the burden on the person using the tool to create the regular expression, but if that was tested in advance and carefully created, it would allow the tool to support a much wider variety of fragment checks.

**Comment by bristola** [comment]
To count the number of matches a user input regular expression are found in a string, we could use the following code:

```python
import re
matches = re.findall(user_input_regex, code_to_check)
num_matches = len(matches)
```

**Comment by Michionlion** [comment]
This kind of code should be integrated into the fragment checks in `fragments.py`.

**Comment by burrowss** [comment]
We are working on implementing regex in the branch for this issue. We are aiming to add these checks into fragments.py and create a new argument to find Latex expressions.

**Comment by Michionlion** [comment]
What exact argument would you need to find Latex expressions? I would be hesitant to add more custom commands if they are not needed.

**Comment by burrowss** [comment]
We could use regular expression fragments to find Latex and add it into the fragments argument if that is a better solution. I was just unsure of whether it was better to make a new argument or add to the fragments

**Comment by Michionlion** [comment]
If it can be accomplished by adding regex support or a new argument for regex support instead of latex specific hard-coded regexes, it should definitely be done without hardcoding.

**Comment by burrowss** [comment]
It should be able to be done with a new argument for regex support so I will look into adding it to the fragment command
