### ISSUE TITLE
Possible bug - check_words does not check for directory or file flags

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgrader#104]
The method is located in [orchestrate.py#L147](https://github.com/GatorEducator/gatorgrader/blob/dc8cb6021c543a0435a0fd11e661158b33db8c86/gator/orchestrate.py#L147).

It seems many other checks are not as fully validated as they should be.

**Comment by gkapfham** [comment]
Hi @Michionlion, I agree that this is the case. With that said, I am thinking that since each linter configuration will be responsible for checking its arguments this issue will be less prevalent once we adopt that new approach. Agreed? I am going to place this on hold for now. We can resume discussion if needed. Otherwise, I judge that we will solve this issue by introducing the new linting interface.

**Comment by Michionlion** [comment]
@gkapfham Is this issue solved by the new linting interface?

**Comment by gkapfham** [comment]
Hi @Michionlion, yes, I think that it should be solved.
