### ISSUE TITLE
Fix markdown in README

### ISSUE THREAD

**Issue by corlettim** [GatorEducator/gatorgrader#139]
Typing errors within the README file such as a lowercase g for Git as well as a bad order of information  like the introduction to starter repos being too far down in the README. They should be towards the start of the README because that is what users will have to reference.

**Comment by Michionlion** [comment]
@corlettim this issue needs more clarity -- where are what exactly are the problems?

**Comment by corlettim** [comment]
@Michionlion is that ok now?

**Comment by gkapfham** [comment]
Hello @corlettim can you please specifically mention the improvements that you think are important to make about the execution of the test suite. It might help us to work on this together if you made a list of the changes that you would like to introduce to the documentation. Thanks for your help on this!

Also, @schultzh I think that you have some new ideas for improving the documentation. Could I trouble you to please open a new issue so that we can discuss your changes as well? Thanks again!

**Comment by gkapfham** [comment]
I think that @corlettim has made a lot of improvements to the README file. I am going to make some more improvements today in a new PR and then close this issue. Let me know if there are other changes that you would like to see me make in the README, okay @Michionlion and @alexheinle and @schultzh?

**Comment by schultzh** [comment]
I think all the changes look great! I like the way the comparison to other tools is set up and explained. Great job @corlettim!

**Comment by gkapfham** [comment]
This issue is resolved by PR #181.
