### ISSUE TITLE
Example repos to show what happens when checks pass and when they do not

### ISSUE THREAD

**Issue by corlettim** [GatorEducator/gatorgrader#192]
While this will be a 3 or 4 week long process, we hope to create new example repos since the old examples will break once we merge the new PR. We hope to create a starter and a solution examples. The starter example repo should have an exit of 1, showing that it fails to run. The solution example repo will exit with a 0, showing that it passes.

**Comment by Michionlion** [comment]
These repositories should probably be an update of the old repositories, instead of creating new ones, although much of the configuration is likely to change. We don't want to create too many repositories that it becomes confusing for users! We should also deprecate (and notify visitors) a repository if it is no longer in use, perhaps by using GitHub's archive feature.

**Comment by gkapfham** [comment]
I'm starting new repositories with a new naming convention, content and structure.

For instance,

https://github.com/GatorEducator/java-assignment-solution-100-01

https://github.com/GatorEducator/java-assignment-starter-100-01

Please bear in mind that we need to reference these and other repositories in the `README.md` file.

Later, I would like to have an integration testing tool that can, perhaps, use a tool like `neighbor` to clone them and then run suitable commands.

The idea would be that a "solution" repository would have checks that always pass while a "starter" repository would, by design, fail.

What do you think @corlettim and @alexheinle and @schultzh and @Michionlion?

Here is the reference for the `neighbor` tool:

https://github.com/mccurdyc/neighbor

**Comment by Michionlion** [comment]
I think that sounds good, although we should remove any old repositories that are no longer relevant, or perhaps consolidate them into one for future testing and other needs!

**Comment by gkapfham** [comment]
Thanks @Michionlion I agree with your point. We will try to add new repositories, cleanup the existing ones, move over many repositories to the "Gator Incubator" and tackle other similar small tasks in the next two weeks.
