### ISSUE TITLE
: (colon) in strings cause bug

### ISSUE THREAD

**Issue by schultzh** [GatorEducator/gatorgrader#215]
**Describe the bug**

**To Reproduce**

1. <!-- Replace this text --!>
2. <!-- Replace this text --!>

**Expected behavior**

**Environment**

A concise description of your environment: GatorGrader version, python version,
operating system, etc.

**Additional context**

@gkapfham Could you fill in the specific details you've experienced with this issue?

**Comment by Michionlion** [comment]
Does this happen when a colon is in a string in `gatorgrader.yml`? If so, it is extremely likely the bug is somewhere in GatorGradle, possibly [ConfigMap#parseBody](https://github.com/GatorEducator/gatorgradle/blob/master/src/main/java/org/gatorgradle/config/ConfigMap.java#L201). That section of the parsing algorithm could definitely use some improvement and testing as well!

**Comment by Michionlion** [comment]
This bug has been squashed in the final release of GatorGradle, and never existed for GatorGrade.
