### ISSUE TITLE
Atomic checks

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgrader#25]
Checks should be formatted so that one GatorGrader command-line call only executes one check, regardless of whether files or directories exist, or any other check. This will involve heavily refactoring `gatorgrader.py` to support individual checks and eliminating code that provides for multi-check commands. In the future, perhaps an option can be implemented to allow for multicheck commands (such as checking for paragraphs and word counts at once), but for now checks should be atomic so that they work well with external tools such as [GatorGradle](https://gatored.github.io/gatorgradle/).

**Comment by gkapfham** [comment]
Hello @Michionlion, @toccinAC, and @castellanosr, I have added a feature that allows GatorGrader to return a JSON object instead of text. However, currently there is not yet a command-line argument to enable this feature. Please let me know how you would like to specify that GatorGrader should return JSON instead of plaintext and then we can deploy this feature into use.

**Comment by gkapfham** [comment]
I have completely refactored the GatorGrader command-line interface and the internals so that all of the checks are now atomic. This means that the tool now only allows you to perform _one_ check for each invocation. For instance, this means that you can no longer check if a file exists and look for fragments inside of the file --- this would now be done in two separate checks. Since this feature is implemented, I will close this issue. If you see problems with the current approach, then please comment here or raise another issue.
