### ISSUE TITLE
Introduce parallel test suite execution and measure performance benefits

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#67]
The existing test suite for GatorGrader always takes less than 10 seconds to run, even when it is collecting coverage information for the entire test suite. However, it would be ideal if we could reduce this execution time to less than 2-3 seconds so that the tests can be run on a very regular basis during development. As such, it might be useful to investigate the use of a tool like `xdist` and see whether or not it can run tests in parallel and improve performance.

**Comment by Michionlion** [comment]
I investigated this and it seems that even with a quad-core desktop, using `xdist` actually causes longer test times because of the collection time. Although `xdist` is now supported (one can simply add `-n auto`, it is not the optimal execution strategy. `xdist` is also not specified in the current `Pipfile`, so would need to be added by each individual developer who wanted to use it.
