### ISSUE TITLE
Consider the adoption of a general-purpose Markdown parser

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrader#81]
There are some current issues, like #45 and #73, that will require us to revisit the way in which we parse the Markdown content. Currently, this parsing happens through the use of regular expressions. In the future, it would be much better to use a Python-based Markdown parser that produces a parse tree. We can then traverse this parse tree and check that the correct aspects of Markdown are evident. Ultimately, this approach is the most likely to support flexible and correct checking of Markdown files.

**Comment by gkapfham** [comment]
I should further note that I have seen that a paragraph check will count a single line with a link on it as a paragraph. Should the check count that as a paragraph or not? The problem is that some one may write a single line with a link as a kind of "list" and this would then cause the check to fail. I should also note that a Markdown list is likely to also be counted as a paragraph and this too is incorrect!

Overall, there is a lot of evidence that we need to introduce a Markdown parser instead of using regular expressions for these types of checks.

**Comment by lylet-AC** [comment]
Saejin and I discussed different options for a Python based markdown parser.  Some options we came up with were CommonMark, Python-Markdown, and mistletoe.  Saejin will follow up with a picture of the different supported outputs.  Additionally we found a link to the markdown ast documentation here: https://github.com/syntax-tree/mdast

**Comment by Michionlion** [comment]
![Documentation](http://i.imgur.com/X21ZrnP.jpg)

**Comment by lylet-AC** [comment]
For finding information in JSON files, @gkapfham recommended [JQ](https://stedolan.github.io/jq/) or [glom](https://github.com/mahmoud/glom).

**Comment by gkapfham** [comment]
Hello @lylet-AC, if you and your colleagues gain some experience with these tools, please report back here! There are several others in our organization who are consider Glom for various parsing purposes.

**Comment by Michionlion** [comment]
@gkapfham, we are actually moving away from glom and tools like it to read Jason, drive with more research, we determined that it was actually possible to remove the intermediate data representation step (json) and simply directly interface with the generated AST.

**Comment by gkapfham** [comment]
Thanks for the update @Michionlion, using the AST directly sounds fine with me. Once there are basic features to test, please point me in the direction of the correct branch and/or PR and I can test this new feature and provide feedback. Perhaps you can demonstrate some preliminary feature this week on Thursday? That is, maybe you could show the input Markdown file, the output AST, and a step in the direction of traversing the AST to perform hard-coded checks? Let me know what is feasible!

**Comment by Michionlion** [comment]
Certainly! Let me outline the plan that my team created to tackle the issue.

First, since the documentation is nonexistent for CommonMark-py, a sub-team will tackle the job of figuring out the API and specification. Then, an implementation team will start work on possible solutions, while the API team assists them (in finding definitions, etc.). Finally, a code review team will review produced code and refer it back to the implementation team for any final changes. We hope to have at least the first two teams' job completed by Thursday, and be working on finalizing changes.

@shafferz's team is working on testing tools for this implementation task -- they're currently putting together test examples, and will later formulate pytest cases for the implementation, possibly early next week. @shafferz and I are coordinating to ensure both teams have the necessary knowledge to carry out these tasks.

Looking forward to showing some developed features next week!

**Comment by huangs1** [comment]
This is the psuedocode that we created to replace the function `get_paragraph()` in `fragments.py`.
```
modes: looking, saving
current mode is looking
counter = 0
paragraph list = []
for all subnodes in ast
    if mode is looking
        if counter is 1 and nodetype is paragraph and enter is true
            set mode to saving
    otherwise if mode is saving
        if counter is 2 and nodetype is paragraph and enter is false
            put saved paragraph in paragraph list
            set mode to looking
        if node has content, add content to saved paragraph
    if nodetype is not a single node
        if enter is true
           increment counter
        otherwise
           decrement counter
return paragraph list
```
