### ISSUE TITLE
Organize the master branch by tagging releases

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgrader#85]
Tagging releases with a tag such as `v1.2.4` (`vmajor.minor.patch`) would enable version pinning, so that backwards compatibility is not always absolutely essential, and any future changes only apply to future labs. In order to accomplish this, we should only need to tag commits with the correct version using `git tag <version>`, however this should be automated, which requires some consideration of how the current version should be stored, and what should increment it. A [related issue (#30)](https://github.com/GatorEducator/gatorgradle/issues/30) in the GatorGradle repository also tracks support for such a feature in GatorGradle.

**Comment by Michionlion** [comment]
There isn't actually a need to release anything -- simply tagging a commit with the relevant version for that commit would be a "release", since gatorgrader is not released in a binary or other build-able format.

**Comment by gkapfham** [comment]
Thanks for clarifying this @Michionlion. We should talk briefly in person about the issue to decide the best path forward. I'm also wondering whether it *would* be a good idea to tag and then release, say, an archive of all of the files? This would then make it possible for people who do not know how to use Git, but do know how to use Python and Pipenv, to install and use our tool. What is the best path forward for this issue if we want to see the broadest adoption of our tool at other institutions?

**Comment by Michionlion** [comment]
I think we need to explore how to make gatorgrader a `pip` package. That is probably the best way forward in this regard.

**Comment by gkapfham** [comment]
Okay, that is also what I was thinking. I think that there are a bunch of tools and approaches that can help.

References:

http://brunorocha.org/python/publish-your-python-packages-easily-using-flit.html
https://realpython.com/pypi-publish-python-package/

I think that we can de-prioritize this task for right now. Is that okay with you @Michionlion?

**Comment by Michionlion** [comment]
For right now, I agree.

**Comment by gkapfham** [comment]
Just as a reminder, if we want to actually perform a release of files through GitHub, then I recall that this will involve creating a certain type of .tar.gz file and then a wheel. Those are the types of files that are uploaded to https://pypi.org/. Again, using tools like Flit might help. We can also consider using Poetry instead of Pipenv, or perhaps, using both Poetry and Pipenv or both Flit and Pipenv. Overall, I don't think that Pipenv supports the uploading to PyPi. Additional references:

https://github.com/pypa/pipenv/issues/2805
https://docs.openstack.org/pbr/latest/
https://github.com/pypa/pipenv/issues/1851

(There are also a wide variety of other references).
